2021-05-30 19:16:12,785:__main__:Tried to divide by zero
2021-05-30 19:17:24,984:__main__:Tried to divide by zero
Traceback (most recent call last):
  File "/home/praveenstein/PycharmProjects/pythonProject_1/firstProject/q5_sample-log.py", line 38, in divide
    result = x / y
ZeroDivisionError: division by zero
